### ISSUE TITLE
TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by Jiahe-Sun** [BGI-Qingdao/VT3D#1]
尊敬的开发团队您好, 
           
      我在运行‘../VT3D/vt3d  Auxiliary GrayScaleTIF -i  hypo_preoptic.h5ad  -o test3d -c  hypo_preoptic.organ.json’ 实例数据构建表面模型时,提示了未知错误, 能否给出相应的解决方案呢? 

     谢谢,期待你的回复.

Jiahe.

日志如下: 
(vitessce) sun@sun-A320MH:~/vitessce_demo/hypo_preoptic$ ../VT3D/vt3d  Auxiliary GrayScaleTIF -i  hypo_preoptic.h5ad  -o test3d -c  hypo_preoptic.organ.json
Traceback (most recent call last):
  File "/home/sunjaihe/vitessce_demo/hypo_preoptic/../VT3D/vt3d", line 49, in <module>
    Auxiliary_main(sys.argv[2:])
  File "/home/sunjaihe/vitessce_demo/VT3D/vt3d_tools/auxiliary.py", line 34, in Auxiliary_main
    grayscaletif_main(argv[1:])
  File "/home/sunjaihe/vitessce_demo/VT3D/vt3d_tools/grayscaletif.py", line 214, in grayscaletif_main
    bin3d.save_coordconf(f'{prefix}.coord.json')
  File "/home/sunjaihe/vitessce_demo/VT3D/vt3d_tools/grayscaletif.py", line 144, in save_coordconf
    savedata2json(conf,filename)
  File "/home/sunjaihe/vitessce_demo/VT3D/vt3d_tools/grayscaletif.py", line 11, in savedata2json
    text = json.dumps(data)
  File "/home/sunjaihe/miniconda3/envs/vitessce/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/sunjaihe/miniconda3/envs/vitessce/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/sunjaihe/miniconda3/envs/vitessce/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/sunjaihe/miniconda3/envs/vitessce/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable

**Comment by Jiahe-Sun** [comment]
已解决;

经排查发现可以 使用 int() 函数将 int64 类型转换为 Python 的 int 类型, 规避此错误;

修改源代码即可:  vim /home/sunjaihe/vitessce_demo/VT3D/vt3d_tools/grayscaletif.py
